development:
  adapter: postgresql
  encoding: unicode
  database: albertico_development
  pool: 5
  timeout: 5000
  username: amb110395
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: albertico_test
  pool: 5
  timeout: 5000
  username: amb110395
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: albertico_production
  pool: 5
  timeout: 5000
  username: amb110395
  password:
